name: Deploy to Heroku
on:
  push:
    branches:
      - main
jobs:
  deploy_to_heroku:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        env:
          cache-hash: ${{ hashFiles('pnpm-lock.yaml') }}
        with:
          path: ~/.pnpm-store
          key: pnpm-os_${{ runner.os }}-node_${{ matrix.node }}-lock_${{ env.cache-hash }}
          restore-keys: |
            pnpm-os_${{ runner.os }}-node_${{ matrix.node }}-
            pnpm-os_${{ runner.os }}-
            pnpm-

      - name: Pull dependencies
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.3.0
          run_install: true

      - name: Build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          npm run build

      - name: Login to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ""
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          justlogin: true

      - name: Package and deploy
        run: |
          heroku container:login
          heroku container:push -a '${{ secrets.HEROKU_APP_NAME }}' web
          heroku container:release -a '${{ secrets.HEROKU_APP_NAME }}' web
